// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5-hS344o96OF-xjYZ38rL-256z841RVM',
    appId: '1:220850908205:web:3069488df21cbda1db1ca4',
    messagingSenderId: '220850908205',
    projectId: 'nonjion',
    authDomain: 'nonjion.firebaseapp.com',
    storageBucket: 'nonjion.firebasestorage.app',
    measurementId: 'G-3JFRZDBMSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1ebgFwyXLa_gjhySBXi5Z-1so_Y4H_Ac',
    appId: '1:220850908205:android:2bcd02e5b1b7eb56db1ca4',
    messagingSenderId: '220850908205',
    projectId: 'nonjion',
    storageBucket: 'nonjion.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5-hS344o96OF-xjYZ38rL-256z841RVM',
    appId: '1:220850908205:web:e3dc25862158dd62db1ca4',
    messagingSenderId: '220850908205',
    projectId: 'nonjion',
    authDomain: 'nonjion.firebaseapp.com',
    storageBucket: 'nonjion.firebasestorage.app',
    measurementId: 'G-8Q11VZ680X',
  );
}
